In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("Dataset/NIFTY50_all.csv")
print(df.head())

         Date      Symbol Series  Prev Close    Open     High    Low   Last  \
0  2007-11-27  MUNDRAPORT     EQ      440.00  770.00  1050.00  770.0  959.0
1  2007-11-28  MUNDRAPORT     EQ      962.90  984.00   990.00  874.0  885.0
2  2007-11-29  MUNDRAPORT     EQ      893.90  909.00   914.75  841.0  887.0
3  2007-11-30  MUNDRAPORT     EQ      884.20  890.00   958.00  890.0  929.0
4  2007-12-03  MUNDRAPORT     EQ      921.55  939.75   995.00  922.0  980.0

    Close    VWAP    Volume      Turnover  Trades  Deliverable Volume  \
0  962.90  984.72  27294366  2.687719e+15     NaN           9859619.0
1  893.90  941.38   4581338  4.312765e+14     NaN           1453278.0
2  884.20  888.09   5124121  4.550658e+14     NaN           1069678.0
3  921.55  929.17   4609762  4.283257e+14     NaN           1260913.0
4  969.30  965.65   2977470  2.875200e+14     NaN            816123.0

   %Deliverble
0       0.3612
1       0.3172
2       0.2088
3       0.2735
4       0.2741

In [3]:
df.shape
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 235192 entries, 0 to 235191
Data columns (total 15 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Date                235192 non-null  str
 1   Symbol              235192 non-null  str
 2   Series              235192 non-null  str
 3   Prev Close          235192 non-null  float64
 4   Open                235192 non-null  float64
 5   High                235192 non-null  float64
 6   Low                 235192 non-null  float64
 7   Last                235192 non-null  float64
 8   Close               235192 non-null  float64
 9   VWAP                235192 non-null  float64
 10  Volume              235192 non-null  int64
 11  Turnover            235192 non-null  float64
 12  Trades              120344 non-null  float64
 13  Deliverable Volume  219115 non-null  float64
 14  %Deliverble         219115 non-null  float64
dtypes: float64(11), int64(1), str(3)
memory usage: 26.9 MB

,Prev Close,Open,High,Low,Last,Close,VWAP,Volume,Turnover,Trades,Deliverable Volume,%Deliverble
count,235192.000000,235192.000000,235192.000000,235192.000000,235192.000000,235192.000000,235192.00000,2.351920e+05,2.351920e+05,1.203440e+05,2.191150e+05,219115.000000
mean,1266.196349,1267.759708,1286.581440,1247.488465,1266.388302,1266.554351,1267.13230,3.045903e+06,1.610138e+14,6.196427e+04,1.315098e+06,0.502997
std,2581.370320,2585.259609,2619.649216,2546.621396,2581.392543,2582.140942,2582.69998,7.333981e+06,3.298085e+14,6.866457e+04,2.831670e+06,0.190019
min,0.000000,8.500000,9.750000,8.500000,9.100000,9.150000,9.21000,3.000000e+00,1.047000e+07,1.100000e+01,5.000000e+00,0.023600
25%,274.300000,275.000000,279.500000,269.600000,274.400000,274.350000,274.69750,2.190095e+05,1.612816e+13,2.183400e+04,1.253830e+05,0.364700
50%,566.500000,567.025000,576.900000,556.500000,567.000000,566.700000,566.94000,1.010938e+06,6.832603e+13,4.406800e+04,5.017560e+05,0.511000
75%,1242.200000,1243.312500,1263.000000,1221.650000,1242.900000,1242.400000,1242.66250,3.019851e+06,1.863835e+14,7.893550e+04,1.452233e+06,0.638400
max,32861.950000,33399.950000,33480.000000,32468.100000,32849.000000,32861.950000,32975.24000,4.810589e+08,3.564334e+16,1.643015e+06,2.325307e+08,1.000000

In [4]:
df["Symbol"].unique()

<StringArray>
['MUNDRAPORT', 'ADANIPORTS', 'ASIANPAINT',    'UTIBANK',   'AXISBANK',
 'BAJAJ-AUTO', 'BAJAJFINSV', 'BAJAUTOFIN', 'BAJFINANCE',     'BHARTI',
 'BHARTIARTL',       'BPCL',  'BRITANNIA',      'CIPLA',  'COALINDIA',
    'DRREDDY',  'EICHERMOT',       'GAIL',     'GRASIM',    'HCLTECH',
       'HDFC',   'HDFCBANK',  'HEROHONDA', 'HEROMOTOCO',   'HINDALC0',
   'HINDALCO',  'HINDLEVER', 'HINDUNILVR',  'ICICIBANK', 'INDUSINDBK',
 'INFOSYSTCH',       'INFY',        'IOC',        'ITC',     'JSWSTL',
   'JSWSTEEL',   'KOTAKMAH',  'KOTAKBANK',         'LT',        'M&M',
     'MARUTI',  'NESTLEIND',       'NTPC',       'ONGC',  'POWERGRID',
   'RELIANCE',       'SBIN',   'SHREECEM',  'SUNPHARMA',      'TELCO',
 'TATAMOTORS',      'TISCO',  'TATASTEEL',        'TCS',      'TECHM',
      'TITAN', 'ULTRACEMCO',    'UNIPHOS',        'UPL',    'SESAGOA',
       'SSLT',       'VEDL',      'WIPRO',    'ZEETELE',       'ZEEL']
Length: 65, dtype: str

In [5]:
df.tail()

,Date,Symbol,Series,Prev Close,Open,High,Low,Last,Close,VWAP,Volume,Turnover,Trades,Deliverable Volume,%Deliverble
235187,2021-04-26,ZEEL,EQ,188.00,190.6,191.10,185.10,186.70,186.40,187.35,8542755,1.600451e+14,52374.0,2340188.0,0.2739
235188,2021-04-27,ZEEL,EQ,186.40,188.0,192.95,186.80,188.80,188.15,189.41,14247767,2.698636e+14,73673.0,5425957.0,0.3808
235189,2021-04-28,ZEEL,EQ,188.15,188.8,190.60,187.10,188.95,189.10,188.85,8429439,1.591917e+14,44056.0,2413974.0,0.2864
235190,2021-04-29,ZEEL,EQ,189.10,190.8,191.65,186.00,186.60,186.55,187.44,9483009,1.777471e+14,60932.0,2744472.0,0.2894
235191,2021-04-30,ZEEL,EQ,186.55,185.3,190.95,183.65,185.00,185.60,187.53,11435285,2.144440e+14,62607.0,3323909.0,0.2907

In [6]:
df.head()
df.tail()
df.nunique()

Date                    5306
Symbol                    65
Series                     1
Prev Close             63729
Open                   44298
High                   49036
Low                    51335
Last                   48570
Close                  63739
VWAP                  138831
Volume                220434
Turnover              235184
Trades                 79112
Deliverable Volume    199963
%Deliverble             9456
dtype: int64

In [7]:
print(df["Date"].nunique())

5306

In [8]:
print(df['Date'].min())
print(df['Date'].max())

2000-01-03
2021-04-30

In [9]:
df.groupby('Date')['Symbol'].nunique().describe()

count    5306.000000
mean       44.325669
std         6.205547
min        28.000000
25%        42.000000
50%        48.000000
75%        49.000000
max        49.000000
Name: Symbol, dtype: float64

In [10]:
df.groupby('Symbol')['Date'].count().sort_values()

Symbol
JSWSTL         123
SSLT           388
KOTAKMAH       502
TELCO          999
MUNDRAPORT    1023
              ...
RELIANCE      5306
SUNPHARMA     5306
TITAN         5306
BPCL          5306
WIPRO         5306
Name: Date, Length: 65, dtype: int64

In [11]:
print(df.columns.tolist())

['Date', 'Symbol', 'Series', 'Prev Close', 'Open', 'High', 'Low', 'Last', 'Close', 'VWAP', 'Volume', 'Turnover', 'Trades', 'Deliverable Volume', '%Deliverble']

In [12]:
df.isnull().sum()

Date                       0
Symbol                     0
Series                     0
Prev Close                 0
Open                       0
High                       0
Low                        0
Last                       0
Close                      0
VWAP                       0
Volume                     0
Turnover                   0
Trades                114848
Deliverable Volume     16077
%Deliverble            16077
dtype: int64

In [13]:
import yfinance as yf

data = yf.download(
    "RELIANCE.NS",
    start="2021-05-01",
    end="2026-09-13"
)

print(data.columns)
print(data.head())
print(data.info())

[*********************100%***********************]  1 of 1 completed

MultiIndex([( 'Close', 'RELIANCE.NS'),
            (  'High', 'RELIANCE.NS'),
            (   'Low', 'RELIANCE.NS'),
            (  'Open', 'RELIANCE.NS'),
            ('Volume', 'RELIANCE.NS')],
           names=['Price', 'Ticker'])
Price            Close        High         Low        Open      Volume
Ticker     RELIANCE.NS RELIANCE.NS RELIANCE.NS RELIANCE.NS RELIANCE.NS
Date
2021-05-03  884.206238  893.210546  877.007316  887.343056    23640186
2021-05-04  865.046631  888.155516  862.519150  880.121562    21849830
2021-05-05  866.626404  874.931121  861.187681  868.093276    12393609
2021-05-06  871.546082  873.351468  860.533254  867.416286    14624666
2021-05-07  871.884644  882.671776  869.289412  874.592694    12288548
<class 'pandas.DataFrame'>
DatetimeIndex: 1332 entries, 2021-05-03 to 2026-09-11
Data columns (total 5 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   (Close, RELIANCE.NS)   1332 non-null   float64
 1   (High, RELIANCE.NS)    1332 non-null   float64
 2   (Low, RELIANCE.NS)     1332 non-null   float64
 3   (Open, RELIANCE.NS)    1332 non-null   float64
 4   (Volume, RELIANCE.NS)  1332 non-null   int64
dtypes: float64(4), int64(1)
memory usage: 62.4 KB
None

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 235192 entries, 0 to 235191
Data columns (total 15 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Date                235192 non-null  str
 1   Symbol              235192 non-null  str
 2   Series              235192 non-null  str
 3   Prev Close          235192 non-null  float64
 4   Open                235192 non-null  float64
 5   High                235192 non-null  float64
 6   Low                 235192 non-null  float64
 7   Last                235192 non-null  float64
 8   Close               235192 non-null  float64
 9   VWAP                235192 non-null  float64
 10  Volume              235192 non-null  int64
 11  Turnover            235192 non-null  float64
 12  Trades              120344 non-null  float64
 13  Deliverable Volume  219115 non-null  float64
 14  %Deliverble         219115 non-null  float64
dtypes: float64(11), int64(1), str(3)
memory usage: 26.9 MB

In [15]:
df.isnull().sum()

Date                       0
Symbol                     0
Series                     0
Prev Close                 0
Open                       0
High                       0
Low                        0
Last                       0
Close                      0
VWAP                       0
Volume                     0
Turnover                   0
Trades                114848
Deliverable Volume     16077
%Deliverble            16077
dtype: int64

In [16]:
df.duplicated().sum()

np.int64(0)

In [17]:
df['Date'] = pd.to_datetime(df['Date'])

df.groupby('Symbol')['Date'].agg(['min', 'max', 'count']).sort_values('count')

                  min        max  count
Symbol
JSWSTL     2005-03-23 2005-09-15    123
SSLT       2013-10-04 2015-05-06    388
KOTAKMAH   2000-01-03 2003-04-17    502
TELCO      2000-01-03 2003-12-24    999
MUNDRAPORT 2007-11-27 2012-01-16   1023
...               ...        ...    ...
RELIANCE   2000-01-03 2021-04-30   5306
SUNPHARMA  2000-01-03 2021-04-30   5306
TITAN      2000-01-03 2021-04-30   5306
BPCL       2000-01-03 2021-04-30   5306
WIPRO      2000-01-03 2021-04-30   5306

[65 rows x 3 columns]

In [18]:
df = df.sort_values(['Symbol', 'Date'])

print(df[['Symbol', 'Date']].head(20))

          Symbol       Date
1023  ADANIPORTS 2012-01-17
1024  ADANIPORTS 2012-01-18
1025  ADANIPORTS 2012-01-19
1026  ADANIPORTS 2012-01-20
1027  ADANIPORTS 2012-01-23
1028  ADANIPORTS 2012-01-24
1029  ADANIPORTS 2012-01-25
1030  ADANIPORTS 2012-01-27
1031  ADANIPORTS 2012-01-30
1032  ADANIPORTS 2012-01-31
1033  ADANIPORTS 2012-02-01
1034  ADANIPORTS 2012-02-02
1035  ADANIPORTS 2012-02-03
1036  ADANIPORTS 2012-02-06
1037  ADANIPORTS 2012-02-07
1038  ADANIPORTS 2012-02-08
1039  ADANIPORTS 2012-02-09
1040  ADANIPORTS 2012-02-10
1041  ADANIPORTS 2012-02-13
1042  ADANIPORTS 2012-02-14

In [19]:
df.duplicated(subset=['Date', 'Symbol']).sum()

np.int64(0)

In [20]:
df[['Prev Close', 'Open', 'High', 'Low', 'Close', 'VWAP', 'Volume', 'Turnover']].describe()

,Prev Close,Open,High,Low,Close,VWAP,Volume,Turnover
count,235192.000000,235192.000000,235192.000000,235192.000000,235192.000000,235192.00000,2.351920e+05,2.351920e+05
mean,1266.196349,1267.759708,1286.581440,1247.488465,1266.554351,1267.13230,3.045903e+06,1.610138e+14
std,2581.370320,2585.259609,2619.649216,2546.621396,2582.140942,2582.69998,7.333981e+06,3.298085e+14
min,0.000000,8.500000,9.750000,8.500000,9.150000,9.21000,3.000000e+00,1.047000e+07
25%,274.300000,275.000000,279.500000,269.600000,274.350000,274.69750,2.190095e+05,1.612816e+13
50%,566.500000,567.025000,576.900000,556.500000,566.700000,566.94000,1.010938e+06,6.832603e+13
75%,1242.200000,1243.312500,1263.000000,1221.650000,1242.400000,1242.66250,3.019851e+06,1.863835e+14
max,32861.950000,33399.950000,33480.000000,32468.100000,32861.950000,32975.24000,4.810589e+08,3.564334e+16

In [21]:
(df['Prev Close'] == 0).sum()

np.int64(1)

In [22]:
df[df['Prev Close'] == 0][['Date', 'Symbol', 'Prev Close', 'Open', 'Close']]

            Date  Symbol  Prev Close  Open  Close
25572 2002-02-18  BHARTI         0.0  51.9  44.35

In [23]:
df[df['Symbol'] == 'BHARTI'].loc[:, ['Date', 'Prev Close', 'Close']].head(10)

            Date  Prev Close  Close
25572 2002-02-18        0.00  44.35
25573 2002-02-19       44.35  41.70
25574 2002-02-20       41.70  41.25
25575 2002-02-21       41.25  42.40
25576 2002-02-22       42.40  43.30
25577 2002-02-25       43.30  42.80
25578 2002-02-26       42.80  43.60
25579 2002-02-27       43.60  44.65
25580 2002-02-28       44.65  41.50
25581 2002-03-01       41.50  42.50

In [24]:
for col in ['Open', 'High', 'Low', 'Close', 'VWAP']:
    print(col, (df[col] <= 0).sum())

Open 0
High 0
Low 0
Close 0
VWAP 0

In [25]:
df['Series'].value_counts()

Series
EQ    235192
Name: count, dtype: int64

In [26]:
(df.isna().sum() / len(df) * 100).round(2)

Date                   0.00
Symbol                 0.00
Series                 0.00
Prev Close             0.00
Open                   0.00
High                   0.00
Low                    0.00
Last                   0.00
Close                  0.00
VWAP                   0.00
Volume                 0.00
Turnover               0.00
Trades                48.83
Deliverable Volume     6.84
%Deliverble            6.84
dtype: float64

In [27]:
df.groupby('Date')['Symbol'].nunique().describe()

count    5306.000000
mean       44.325669
std         6.205547
min        28.000000
25%        42.000000
50%        48.000000
75%        49.000000
max        49.000000
Name: Symbol, dtype: float64

In [28]:
df.groupby('Symbol')['Date'].agg(['min', 'max', 'count']).sort_values('count')

                  min        max  count
Symbol
JSWSTL     2005-03-23 2005-09-15    123
SSLT       2013-10-04 2015-05-06    388
KOTAKMAH   2000-01-03 2003-04-17    502
TELCO      2000-01-03 2003-12-24    999
MUNDRAPORT 2007-11-27 2012-01-16   1023
...               ...        ...    ...
RELIANCE   2000-01-03 2021-04-30   5306
SUNPHARMA  2000-01-03 2021-04-30   5306
TITAN      2000-01-03 2021-04-30   5306
BPCL       2000-01-03 2021-04-30   5306
WIPRO      2000-01-03 2021-04-30   5306

[65 rows x 3 columns]

In [29]:
df['Symbol'].nunique()

65

In [30]:
df.groupby('Symbol')['Date'].count().sort_values(ascending=False).head(15)

Symbol
ASIANPAINT    5306
SUNPHARMA     5306
GRASIM        5306
CIPLA         5306
BPCL          5306
DRREDDY       5306
IOC           5306
HDFCBANK      5306
HDFC          5306
ICICIBANK     5306
ITC           5306
WIPRO         5306
TITAN         5306
ONGC          5306
RELIANCE      5306
Name: Date, dtype: int64

In [31]:
df['Return'] = df.groupby('Symbol')['Close'].pct_change()

In [32]:
df[['Symbol', 'Date', 'Close', 'Return']].head(10)

          Symbol       Date   Close    Return
1023  ADANIPORTS 2012-01-17  140.00       NaN
1024  ADANIPORTS 2012-01-18  141.70  0.012143
1025  ADANIPORTS 2012-01-19  149.40  0.054340
1026  ADANIPORTS 2012-01-20  155.40  0.040161
1027  ADANIPORTS 2012-01-23  146.75 -0.055663
1028  ADANIPORTS 2012-01-24  150.05  0.022487
1029  ADANIPORTS 2012-01-25  143.20 -0.045651
1030  ADANIPORTS 2012-01-27  147.10  0.027235
1031  ADANIPORTS 2012-01-30  138.40 -0.059143
1032  ADANIPORTS 2012-01-31  146.25  0.056720

In [33]:
df['Return'].describe()

count    235127.000000
mean          0.000688
std           0.027252
min          -0.946849
25%          -0.011136
50%           0.000187
75%           0.012196
max           0.446731
Name: Return, dtype: float64

In [34]:
(df['Return'].abs() > 0.10).sum()

np.int64(1359)

In [35]:
df['Volatility_20'] = (
    df.groupby('Symbol')['Return']
      .transform(lambda x: x.rolling(20).std())
)

In [36]:
df[['Symbol', 'Date', 'Return', 'Volatility_20']].tail(10)

         Symbol       Date    Return  Volatility_20
231672  ZEETELE 2007-02-13  0.037159       0.071533
231673  ZEETELE 2007-02-14 -0.009143       0.071020
231674  ZEETELE 2007-02-15  0.010358       0.071041
231675  ZEETELE 2007-02-19 -0.028891       0.071319
231676  ZEETELE 2007-02-20 -0.041267       0.071760
231677  ZEETELE 2007-02-21  0.021622       0.071760
231678  ZEETELE 2007-02-22 -0.004115       0.071446
231679  ZEETELE 2007-02-23 -0.021055       0.070338
231680  ZEETELE 2007-02-26 -0.017889       0.069502
231681  ZEETELE 2007-02-27 -0.024355       0.069539

In [37]:
df['Volume_MA_20'] = (
    df.groupby('Symbol')['Volume']
      .transform(lambda x: x.rolling(20).mean())
)

In [38]:
df['Volume_Ratio'] = df['Volume'] / df['Volume_MA_20']

In [39]:
df[['Symbol', 'Date', 'Volume', 'Volume_MA_20', 'Volume_Ratio']].tail(10)

         Symbol       Date   Volume  Volume_MA_20  Volume_Ratio
231672  ZEETELE 2007-02-13  2689950    2785672.10      0.965638
231673  ZEETELE 2007-02-14  2820444    2844793.70      0.991441
231674  ZEETELE 2007-02-15  3516748    2989540.85      1.176351
231675  ZEETELE 2007-02-19  1381008    3028194.50      0.456050
231676  ZEETELE 2007-02-20  2017478    3065159.30      0.658197
231677  ZEETELE 2007-02-21  1587042    3058354.45      0.518920
231678  ZEETELE 2007-02-22  2035216    2992196.60      0.680175
231679  ZEETELE 2007-02-23   978816    2757293.20      0.354992
231680  ZEETELE 2007-02-26   833714    2663962.70      0.312960
231681  ZEETELE 2007-02-27  2745979    2629784.80      1.044184

In [40]:
df[['Return', 'Volatility_20', 'Volume_Ratio']].isna().sum()

Return             65
Volatility_20    1300
Volume_Ratio     1235
dtype: int64

In [41]:
features = ['Return', 'Volatility_20', 'Volume_Ratio']

model_df = df.dropna(subset=features).copy()

X = model_df[features]

print(X.shape)

(233892, 3)

In [42]:
train_df = model_df[model_df['Date'] < '2016-01-01']
test_df = model_df[model_df['Date'] >= '2016-01-01']

X_train = train_df[features]
X_test = test_df[features]

print("Train:", X_train.shape)
print("Test:", X_test.shape)

Train: (169310, 3)
Test: (64582, 3)

In [43]:
symbol_map = {
    'MUNDRAPORT': 'ADANIPORTS',
    'BHARTI': 'BHARTIARTL',
    'HEROHONDA': 'HEROMOTOCO',
    'HINDLEVER': 'HINDUNILVR',
    'INFOSYSTCH': 'INFY',
    'TELCO': 'TATAMOTORS',
    'TISCO': 'TATASTEEL',
    'KOTAKMAH': 'KOTAKBANK',
    'BAJAUTOFIN': 'BAJFINANCE',
    'JSWSTL': 'JSWSTEEL',
    'ZEETELE': 'ZEEL',
    'UNIPHOS': 'UPL',
    'HINDALC0': 'HINDALCO',
    'SESAGOA': 'VEDL',
    'SSLT': 'VEDL'
}

df['CanonicalSymbol'] = df['Symbol'].replace(symbol_map)

In [44]:
df['CanonicalSymbol'].nunique()

50

In [45]:
df = df.sort_values(['CanonicalSymbol', 'Date']).copy()

In [46]:
df['Return'] = (
    df.groupby('CanonicalSymbol')['Close']
      .pct_change()
)

In [47]:
df['Volatility_20'] = (
    df.groupby('CanonicalSymbol')['Return']
      .transform(lambda x: x.rolling(20).std())
)

In [48]:
df['Volume_MA_20'] = (
    df.groupby('CanonicalSymbol')['Volume']
      .transform(lambda x: x.rolling(20).mean())
)

df['Volume_Ratio'] = df['Volume'] / df['Volume_MA_20']

In [49]:
features = ['Return', 'Volatility_20', 'Volume_Ratio']

model_df = df.dropna(subset=features).copy()

print(model_df.shape)
print(model_df['CanonicalSymbol'].nunique())

(234192, 20)
50

In [50]:
train_df = model_df[model_df['Date'] < '2016-01-01']
test_df = model_df[model_df['Date'] >= '2016-01-01']

X_train = train_df[features]
X_test = test_df[features]

print("Train:", X_train.shape)
print("Test:", X_test.shape)

Train: (169610, 3)
Test: (64582, 3)

In [51]:
from sklearn.ensemble import IsolationForest

model = IsolationForest(
    n_estimators=200,
    contamination=0.01,
    random_state=42,
    n_jobs=-1
)

model.fit(X_train)

IsolationForest(contamination=0.01, n_estimators=200, n_jobs=-1,
                random_state=42)

In [52]:
test_df = test_df.copy()

test_df['Anomaly'] = model.predict(X_test)
test_df['Anomaly_Score'] = model.decision_function(X_test)

print(test_df['Anomaly'].value_counts())

Anomaly
 1    64236
-1      346
Name: count, dtype: int64

In [53]:
anomalies = test_df[test_df['Anomaly'] == -1]

anomalies[
    ['CanonicalSymbol', 'Date', 'Return',
     'Volatility_20', 'Volume_Ratio', 'Anomaly_Score']
].sort_values('Anomaly_Score').head(20)

,CanonicalSymbol,Date,Return,Volatility_20,Volume_Ratio,Anomaly_Score
59297,EICHERMOT,2020-08-24,-0.899714,0.203676,13.807329,-0.149249
24423,BAJFINANCE,2016-09-08,-0.897940,0.202462,9.192480,-0.148131
68629,GRASIM,2016-10-06,-0.795441,0.179295,6.927341,-0.142281
130724,JSWSTEEL,2017-01-05,0.077277,0.203351,7.490228,-0.135647
130723,JSWSTEEL,2017-01-04,-0.900854,0.201784,4.189882,-0.128520
130728,JSWSTEEL,2017-01-11,0.050995,0.204522,8.258079,-0.126420
234634,ZEEL,2019-01-28,0.172425,0.073455,8.131119,-0.119374
175995,SBIN,2017-10-25,0.276872,0.063890,10.375999,-0.113460
130725,JSWSTEEL,2017-01-06,-0.002562,0.203387,4.887808,-0.107364
85271,HDFCBANK,2019-09-20,0.089505,0.114529,4.710179,-0.105920
24425,BAJFINANCE,2016-09-12,-0.051276,0.202328,4.072165,-0.105654
121719,IOC,2018-03-15,-0.513859,0.116447,3.594803,-0.100546
234633,ZEEL,2019-01-25,-0.266106,0.059943,8.263567,-0.100369
59298,EICHERMOT,2020-08-25,0.018746,0.203571,4.500438,-0.098251
116531,INFY,2018-09-04,-0.486038,0.110044,3.408947,-0.097391
201186,TCS,2018-05-31,-0.504553,0.113628,3.182344,-0.097129
111608,INDUSINDBK,2020-03-26,0.446731,0.136945,2.014109,-0.092362
35017,BPCL,2018-10-05,-0.198852,0.057352,7.005675,-0.091205
209986,TITAN,2017-11-06,0.187874,0.044669,9.411944,-0.090826
111602,INDUSINDBK,2020-03-18,-0.237276,0.068229,5.092818,-0.090577

In [54]:
df[
    (df['CanonicalSymbol'] == 'EICHERMOT') &
    (df['Date'].between('2020-08-20', '2020-08-27'))
][[
    'Date', 'Symbol', 'Close', 'Prev Close',
    'Open', 'High', 'Low', 'Volume', 'Return'
]]

,Date,Symbol,Close,Prev Close,Open,High,Low,Volume,Return
59295,2020-08-20,EICHERMOT,21371.35,21261.35,21200.00,21530.00,20900.00,224320,0.005174
59296,2020-08-21,EICHERMOT,21702.40,21371.35,21700.00,21844.00,21480.00,261318,0.015490
59297,2020-08-24,EICHERMOT,2176.45,21702.40,2199.45,2387.25,2151.70,11491732,-0.899714
59298,2020-08-25,EICHERMOT,2217.25,2176.45,2214.00,2250.00,2182.15,4757114,0.018746
59299,2020-08-26,EICHERMOT,2248.85,2217.25,2280.05,2288.00,2235.00,2439450,0.014252
59300,2020-08-27,EICHERMOT,2236.35,2248.85,2249.75,2255.00,2215.00,1370440,-0.005558

In [55]:
extreme = df[df['Return'].abs() > 0.50].copy()

print("Extreme returns:", len(extreme))

print(
    extreme[
        ['CanonicalSymbol', 'Date', 'Prev Close',
         'Open', 'High', 'Low', 'Close', 'Return']
    ].sort_values('Return').to_string(index=False)
)

Extreme returns: 57
CanonicalSymbol       Date  Prev Close    Open    High     Low   Close    Return
           VEDL 2008-08-08     3306.60  172.80  177.80  166.60  175.75 -0.946849
          TITAN 2011-06-23     4292.45  210.00  234.00  205.00  228.90 -0.946674
            ITC 2005-09-21     1929.60  139.80  141.90  129.40  140.20 -0.927342
       JSWSTEEL 2017-01-04     1644.55  166.75  166.75  160.60  163.05 -0.900854
     ASIANPAINT 2013-07-30     5118.20  521.50  522.40  502.65  510.75 -0.900209
      EICHERMOT 2020-08-24    21702.40 2199.45 2387.25 2151.70 2176.45 -0.899714
     BAJFINANCE 2016-09-08    11393.30 1153.90 1173.60 1080.00 1162.80 -0.897940
           SBIN 2014-11-20     2910.50  294.75  298.75  291.25  297.10 -0.897921
       HINDALCO 2005-08-30     1387.20  145.00  145.00  141.00  141.95 -0.897672
     HINDUNILVR 2000-07-05     2771.70  288.00  289.00  278.00  286.70 -0.896562
     TATAMOTORS 2011-09-12      764.90  145.95  149.20  143.50  146.35 -0.808668
     ADANIPORTS 2010-09-23      837.00  170.55  170.55  163.25  165.60 -0.802151
       AXISBANK 2014-07-28     1985.75  403.45  407.35  393.60  395.35 -0.800906
      SUNPHARMA 2010-11-25     2273.35  455.00  474.75  445.20  454.00 -0.800295
       HDFCBANK 2011-07-14     2519.70  505.10  513.30  498.80  505.95 -0.799202
      ICICIBANK 2014-12-04     1794.10  362.50  366.05  358.35  362.20 -0.798116
         GRASIM 2016-10-06     4933.55  994.00 1019.00  988.20 1009.20 -0.795441
          CIPLA 2004-05-12     1274.55  253.50  264.50  253.50  260.95 -0.795261
     HEROMOTOCO 2001-03-14      804.50  157.00  166.00  156.00  165.25 -0.794593
           HDFC 2010-08-18     3008.95  630.00  668.70  595.25  621.20 -0.793549
            UPL 2005-09-27      989.05  202.00  220.85  200.10  215.90 -0.781710
      BRITANNIA 2010-09-08     2123.25  430.25  499.00  425.15  482.75 -0.772636
           ONGC 2011-02-08     1194.55  300.00  301.00  278.30  282.05 -0.763886
          TECHM 2015-03-19     2800.50  695.00  700.90  685.00  687.15 -0.754633
           INFY 2004-07-01     5524.10 1395.00 1415.70 1359.20 1408.80 -0.744972
      SUNPHARMA 2000-03-08     2023.35  668.00  702.15  601.00  649.80 -0.678849
          WIPRO 2004-06-25     1588.10  570.00  570.00  522.20  533.25 -0.664221
      KOTAKBANK 2001-07-02       48.00   48.05   49.50   48.00   48.05 -0.611246
          CIPLA 2006-04-24      659.50  270.00  270.00  251.10  259.70 -0.606217
      KOTAKBANK 2005-08-25      464.75  210.00  210.00  188.00  202.75 -0.563744
     INDUSINDBK 2001-07-02       13.00   11.05   13.00   11.05   12.70 -0.542342
            M&M 2017-12-21     1541.75  767.00  767.00  738.95  742.20 -0.518599
       RELIANCE 2009-11-26     2194.70 1111.00 1111.00 1053.30 1063.75 -0.515310
            IOC 2018-03-15      395.05  191.00  193.25  189.25  192.05 -0.513859
           BPCL 2016-07-13     1120.55  559.90  563.00  543.60  545.60 -0.513096
           GAIL 2019-07-09      302.10  151.00  152.20  145.75  147.10 -0.513075
             LT 2006-09-28     2589.60 1346.90 1346.90 1259.00 1263.05 -0.512261
        HCLTECH 2015-03-19     2006.55  990.00 1006.40  972.00  979.65 -0.511774
            TCS 2006-07-28     1899.70  940.10  974.95  924.00  928.45 -0.511265
           INFY 2014-12-02     4349.85 2164.95 2164.95 2115.00 2126.60 -0.511110
            IOC 2009-10-29      642.60  312.00  325.95  281.15  314.60 -0.510426
        HCLTECH 2007-03-15      630.60  320.00  320.00  299.00  309.80 -0.508722
      KOTAKBANK 2004-08-25      355.75  170.00  177.85  170.00  174.85 -0.508503
          WIPRO 2017-06-13      526.35  260.00  266.70  256.75  259.00 -0.507932
           BPCL 2012-07-13      785.45  389.90  393.45  385.00  386.55 -0.507862
            ITC 2010-08-03      312.80  158.70  158.70  153.75  154.40 -0.506394
     BAJAJ-AUTO 2010-09-08     2997.40 1501.30 1512.75 1457.40 1480.60 -0.506039
           VEDL 2005-02-16     1496.65  759.00  787.70  733.30  739.45 -0.505930
        HCLTECH 2000-11-29     1306.75  635.00  655.00  629.00  646.25 -0.505452
        DRREDDY 2006-08-28     1443.10  739.00  739.00  703.00  714.15 -0.505128
            TCS 2018-05-31     3514.10 1734.00 1759.05 1726.10 1741.05 -0.504553
      KOTAKBANK 2015-07-08     1425.60  703.85  712.25  693.05  707.10 -0.503998
           INFY 2006-07-13     3385.65 1748.00 1799.00 1666.00 1681.95 -0.503212
             LT 2008-10-01     2446.40 1249.90 1280.00 1152.60 1216.10 -0.502902
       RELIANCE 2017-09-07     1645.40  823.00  832.50  815.00  818.10 -0.502796
           HDFC 2002-12-12      690.35  360.00  360.00  338.05  343.60 -0.502281
        HCLTECH 2019-12-05     1125.50  563.80  567.65  557.15  560.90 -0.501644

In [56]:
extreme['Price_Ratio'] = (
    extreme['Prev Close'] / extreme['Close']
)

extreme[['CanonicalSymbol', 'Date', 'Price_Ratio']] \
    .sort_values('Price_Ratio', ascending=False) \
    .head(30)

       CanonicalSymbol       Date  Price_Ratio
221432            VEDL 2008-08-08    18.814225
208408           TITAN 2011-06-23    18.752512
123930             ITC 2005-09-21    13.763195
130723        JSWSTEEL 2017-01-04    10.086170
6714        ASIANPAINT 2013-07-30    10.020950
59297        EICHERMOT 2020-08-24     9.971467
24423       BAJFINANCE 2016-09-08     9.798160
175270            SBIN 2014-11-20     9.796365
92400         HINDALCO 2005-08-30     9.772455
96409       HINDUNILVR 2000-07-05     9.667597
190076      TATAMOTORS 2011-09-12     5.226512
694         ADANIPORTS 2010-09-23     5.054348
12266         AXISBANK 2014-07-28     5.022765
184572       SUNPHARMA 2010-11-25     5.007379
83246         HDFCBANK 2011-07-14     4.980136
105310       ICICIBANK 2014-12-04     4.953341
68629           GRASIM 2016-10-06     4.888575
42049            CIPLA 2004-05-12     4.884269
85971       HEROMOTOCO 2001-03-14     4.868381
77712             HDFC 2010-08-18     4.843770
215411             UPL 2005-09-27     4.581056
38319        BRITANNIA 2010-09-08     4.398239
160361            ONGC 2011-02-08     4.235242
204029           TECHM 2015-03-19     4.075529
113008            INFY 2004-07-01     3.921139
181896       SUNPHARMA 2000-03-08     3.113804
225704           WIPRO 2004-06-25     2.978153
42538            CIPLA 2006-04-24     2.539469
132891       KOTAKBANK 2005-08-25     2.292232
145438             M&M 2017-12-21     2.077270

In [57]:
extreme['Price_Ratio'] = extreme['Prev Close'] / extreme['Close']

print(
    extreme[
        ['CanonicalSymbol', 'Date', 'Price_Ratio']
    ].sort_values('Price_Ratio', ascending=False).head(30).to_string(index=False)
)

CanonicalSymbol       Date  Price_Ratio
           VEDL 2008-08-08    18.814225
          TITAN 2011-06-23    18.752512
            ITC 2005-09-21    13.763195
       JSWSTEEL 2017-01-04    10.086170
     ASIANPAINT 2013-07-30    10.020950
      EICHERMOT 2020-08-24     9.971467
     BAJFINANCE 2016-09-08     9.798160
           SBIN 2014-11-20     9.796365
       HINDALCO 2005-08-30     9.772455
     HINDUNILVR 2000-07-05     9.667597
     TATAMOTORS 2011-09-12     5.226512
     ADANIPORTS 2010-09-23     5.054348
       AXISBANK 2014-07-28     5.022765
      SUNPHARMA 2010-11-25     5.007379
       HDFCBANK 2011-07-14     4.980136
      ICICIBANK 2014-12-04     4.953341
         GRASIM 2016-10-06     4.888575
          CIPLA 2004-05-12     4.884269
     HEROMOTOCO 2001-03-14     4.868381
           HDFC 2010-08-18     4.843770
            UPL 2005-09-27     4.581056
      BRITANNIA 2010-09-08     4.398239
           ONGC 2011-02-08     4.235242
          TECHM 2015-03-19     4.075529
           INFY 2004-07-01     3.921139
      SUNPHARMA 2000-03-08     3.113804
          WIPRO 2004-06-25     2.978153
          CIPLA 2006-04-24     2.539469
      KOTAKBANK 2005-08-25     2.292232
            M&M 2017-12-21     2.077270

In [58]:
df[
    (df['CanonicalSymbol'] == 'JSWSTEEL') &
    (df['Date'].between('2017-01-03', '2017-01-06'))
][[
    'Date', 'Prev Close', 'Open', 'High', 'Low', 'Close'
]]

             Date  Prev Close     Open     High      Low    Close
130722 2017-01-03     1634.30  1641.00  1653.60  1631.00  1644.55
130723 2017-01-04     1644.55   166.75   166.75   160.60   163.05
130724 2017-01-05      163.05   164.05   176.65   163.50   175.65
130725 2017-01-06      175.65   177.35   178.80   172.75   175.20

In [59]:
df['PrevClose_Open_Ratio'] = df['Prev Close'] / df['Open']

df['Structural_Break'] = (
    (df['PrevClose_Open_Ratio'] > 1.5) |
    (df['PrevClose_Open_Ratio'] < 0.67)
)

print("Potential structural breaks:",
      df['Structural_Break'].sum())

Potential structural breaks: 95

In [60]:
df[df['Structural_Break']][
    ['CanonicalSymbol', 'Date', 'Prev Close',
     'Open', 'High', 'Low', 'Close',
     'PrevClose_Open_Ratio']
].head(30)

,CanonicalSymbol,Date,Prev Close,Open,High,Low,Close,PrevClose_Open_Ratio
0,ADANIPORTS,2007-11-27,440.00,770.00,1050.00,770.00,962.90,0.571429
694,ADANIPORTS,2010-09-23,837.00,170.55,170.55,163.25,165.60,4.907652
3468,ASIANPAINT,2000-08-02,464.00,272.00,279.00,268.50,272.10,1.705882
4232,ASIANPAINT,2003-08-22,435.85,288.00,299.05,272.00,293.95,1.513368
6714,ASIANPAINT,2013-07-30,5118.20,521.50,522.40,502.65,510.75,9.814382
12266,AXISBANK,2014-07-28,1985.75,403.45,407.35,393.60,395.35,4.921923
13934,BAJAJ-AUTO,2008-05-26,2101.05,898.00,898.00,551.35,604.75,2.339699
14498,BAJAJ-AUTO,2010-09-08,2997.40,1501.30,1512.75,1457.40,1480.60,1.996536
17136,BAJAJFINSV,2008-05-26,2101.05,600.00,619.00,501.00,509.10,3.501750
24423,BAJFINANCE,2016-09-08,11393.30,1153.90,1173.60,1080.00,1162.80,9.873733
25572,BHARTIARTL,2002-02-18,0.00,51.90,51.90,43.50,44.35,0.000000
27428,BHARTIARTL,2009-07-24,814.10,419.70,425.90,400.15,415.95,1.939719
30589,BPCL,2000-12-20,248.90,126.40,127.80,122.05,125.15,1.969146
33477,BPCL,2012-07-13,785.45,389.90,393.45,385.00,386.55,2.014491
34464,BPCL,2016-07-13,1120.55,559.90,563.00,543.60,545.60,2.001340
38319,BRITANNIA,2010-09-08,2123.25,430.25,499.00,425.15,482.75,4.934922
40358,BRITANNIA,2018-11-29,5961.75,3016.00,3045.00,2985.00,3032.35,1.976708
42049,CIPLA,2004-05-12,1274.55,253.50,264.50,253.50,260.95,5.027811
42538,CIPLA,2006-04-24,659.50,270.00,270.00,251.10,259.70,2.442593
49308,DRREDDY,2001-10-15,1853.40,930.00,938.00,923.10,927.10,1.992903
50532,DRREDDY,2006-08-28,1443.10,739.00,739.00,703.00,714.15,1.952774
54542,EICHERMOT,2001-07-02,32.50,20.50,21.20,20.50,21.00,1.585366
59297,EICHERMOT,2020-08-24,21702.40,2199.45,2387.25,2151.70,2176.45,9.867194
61343,GAIL,2008-10-06,393.80,250.00,267.00,248.00,251.85,1.575200
64004,GAIL,2019-07-09,302.10,151.00,152.20,145.75,147.10,2.000662
68629,GRASIM,2016-10-06,4933.55,994.00,1019.00,988.20,1009.20,4.963330
69759,HCLTECH,2000-01-11,580.00,1550.00,1725.00,1492.00,1554.45,0.374194
69981,HCLTECH,2000-11-29,1306.75,635.00,655.00,629.00,646.25,2.057874
71560,HCLTECH,2007-03-15,630.60,320.00,320.00,299.00,309.80,1.970625
73546,HCLTECH,2015-03-19,2006.55,990.00,1006.40,972.00,979.65,2.026818

In [61]:
df[df['Structural_Break']][
    ['CanonicalSymbol', 'Date',
     'Prev Close', 'Open', 'Close',
     'PrevClose_Open_Ratio']
].sort_values('PrevClose_Open_Ratio').to_string(index=False)

'CanonicalSymbol       Date  Prev Close    Open   Close  PrevClose_Open_Ratio\n     BHARTIARTL 2002-02-18        0.00   51.90   44.35              0.000000\n             LT 2004-06-23        2.00  500.00  635.95              0.004000\n       JSWSTEEL 2005-03-23       10.00  455.00  390.15              0.021978\n     ULTRACEMCO 2004-08-24       10.00  305.00  260.20              0.032787\n            UPL 2004-01-23       10.00  100.00  553.80              0.100000\n        HCLTECH 2000-01-11      580.00 1550.00 1554.45              0.374194\n     ADANIPORTS 2007-11-27      440.00  770.00  962.90              0.571429\n      POWERGRID 2007-10-05       52.00   89.80  100.60              0.579065\n           ONGC 2006-10-27     1153.90  767.30  789.50              1.503845\n           ONGC 2016-12-15      305.30  202.80  206.45              1.505424\n     ASIANPAINT 2003-08-22      435.85  288.00  293.95              1.513368\n            ITC 2016-07-01      368.40  243.30  252.35              1.514180\n           GAIL 2008-10-06      393.80  250.00  251.85              1.575200\n      EICHERMOT 2001-07-02       32.50   20.50   21.00              1.585366\n          WIPRO 2010-06-15      674.20  422.40  408.20              1.596117\n       RELIANCE 2006-01-18      928.50  580.10  693.70              1.600586\n           ZEEL 2007-02-12      361.30  225.25  258.35              1.603996\n            IOC 2003-08-14      518.60  321.30  333.00              1.614068\n     ASIANPAINT 2000-08-02      464.00  272.00  272.10              1.705882\n           INFY 2000-01-27    14109.40 7570.00 7390.75              1.863857\n            UPL 2008-10-29      165.70   88.00   84.55              1.882955\n           ZEEL 2010-11-11      295.10  155.00  147.60              1.903871\n           HDFC 2002-12-12      690.35  360.00  343.60              1.917639\n             LT 2006-09-28     2589.60 1346.90 1263.05              1.922637\n           INFY 2006-07-13     3385.65 1748.00 1681.95              1.936871\n     BHARTIARTL 2009-07-24      814.10  419.70  415.95              1.939719\n        DRREDDY 2006-08-28     1443.10  739.00  714.15              1.952774\n          WIPRO 2005-08-22      720.05  368.50  362.55              1.954003\n             LT 2008-10-01     2446.40 1249.90 1216.10              1.957277\n      SUNPHARMA 2003-01-13      583.00  296.75  295.10              1.964617\n            M&M 2005-09-01      721.20  367.00  362.40              1.965123\n           BPCL 2000-12-20      248.90  126.40  125.15              1.969146\n        HCLTECH 2007-03-15      630.60  320.00  309.80              1.970625\n            ITC 2010-08-03      312.80  158.70  154.40              1.971014\n           VEDL 2005-02-16     1496.65  759.00  739.45              1.971871\n       RELIANCE 2009-11-26     2194.70 1111.00 1063.75              1.975428\n      KOTAKBANK 2010-09-13      864.60  437.55  454.70              1.976003\n      BRITANNIA 2018-11-29     5961.75 3016.00 3032.35              1.976708\n      SUNPHARMA 2013-07-29     1117.30  565.00  569.25              1.977522\n            M&M 2010-03-29     1080.90  546.20  553.60              1.978945\n           INFY 2018-09-04     1434.25  722.00  737.15              1.986496\n            IOC 2016-10-18      642.30  323.00  321.70              1.988545\n       HDFCBANK 2019-09-19     2187.75 1099.90 1101.05              1.989044\n        DRREDDY 2001-10-15     1853.40  930.00  927.10              1.992903\n      SUNPHARMA 2004-05-27      762.25  382.00  398.20              1.995419\n        HCLTECH 2019-12-05     1125.50  563.80  560.90              1.996275\n     BAJAJ-AUTO 2010-09-08     2997.40 1501.30 1480.60              1.996536\n       RELIANCE 2017-09-07     1645.40  823.00  818.10              1.999271\n           GAIL 2019-07-09      302.10  151.00  147.10              2.000662\n           BPCL 2016-07-13     1120.55  559.90  545.60              2.001340\n           INFY 2014-12-02     4349.85 2164.95 2126.60              2.009215\n            M&M 2017-12-21     1541.75  767.00  742.20              2.010104\n           BPCL 2012-07-13      785.45  389.90  386.55              2.014491\n            TCS 2006-07-28     1899.70  940.10  928.45              2.020742\n           INFY 2015-06-15     1975.05  976.95  990.45              2.021649\n          WIPRO 2017-06-13      526.35  260.00  259.00              2.024423\n      KOTAKBANK 2015-07-08     1425.60  703.85  707.10              2.025432\n            TCS 2018-05-31     3514.10 1734.00 1741.05              2.026586\n        HCLTECH 2015-03-19     2006.55  990.00  979.65              2.026818\n            TCS 2009-06-16      778.00  383.30  389.15              2.029742\n        HCLTECH 2000-11-29     1306.75  635.00  646.25              2.057874\n            IOC 2009-10-29      642.60  312.00  314.60              2.059615\n            IOC 2018-03-15      395.05  191.00  192.05              2.068325\n      KOTAKBANK 2004-08-25      355.75  170.00  174.85              2.092647\n      KOTAKBANK 2005-08-25      464.75  210.00  202.75              2.213095\n     BAJAJ-AUTO 2008-05-26     2101.05  898.00  604.75              2.339699\n          CIPLA 2006-04-24      659.50  270.00  259.70              2.442593\n          WIPRO 2004-06-25     1588.10  570.00  533.25              2.786140\n      SUNPHARMA 2000-03-08     2023.35  668.00  649.80              3.028967\n     BAJAJFINSV 2008-05-26     2101.05  600.00  509.10              3.501750\n           INFY 2004-07-01     5524.10 1395.00 1408.80              3.959928\n           ONGC 2011-02-08     1194.55  300.00  282.05              3.981833\n          TECHM 2015-03-19     2800.50  695.00  687.15              4.029496\n           HDFC 2010-08-18     3008.95  630.00  621.20              4.776111\n            UPL 2005-09-27      989.05  202.00  215.90              4.896287\n     ADANIPORTS 2010-09-23      837.00  170.55  165.60              4.907652\n       AXISBANK 2014-07-28     1985.75  403.45  395.35              4.921923\n      BRITANNIA 2010-09-08     2123.25  430.25  482.75              4.934922\n      ICICIBANK 2014-12-04     1794.10  362.50  362.20              4.949241\n         GRASIM 2016-10-06     4933.55  994.00 1009.20              4.963330\n       HDFCBANK 2011-07-14     2519.70  505.10  505.95              4.988517\n      SUNPHARMA 2010-11-25     2273.35  455.00  454.00              4.996374\n          CIPLA 2004-05-12     1274.55  253.50  260.95              5.027811\n     HEROMOTOCO 2001-03-14      804.50  157.00  165.25              5.124204\n     TATAMOTORS 2011-09-12      764.90  145.95  146.35              5.240836\n       HINDALCO 2005-08-30     1387.20  145.00  141.95              9.566897\n     HINDUNILVR 2000-07-05     2771.70  288.00  286.70              9.623958\n     ASIANPAINT 2013-07-30     5118.20  521.50  510.75              9.814382\n       JSWSTEEL 2017-01-04     1644.55  166.75  163.05              9.862369\n      EICHERMOT 2020-08-24    21702.40 2199.45 2176.45              9.867194\n     BAJFINANCE 2016-09-08    11393.30 1153.90 1162.80              9.873733\n           SBIN 2014-11-20     2910.50  294.75  297.10              9.874470\n            ITC 2005-09-21     1929.60  139.80  140.20             13.802575\n           VEDL 2008-08-08     3306.60  172.80  175.75             19.135417\n          TITAN 2011-06-23     4292.45  210.00  228.90             20.440238'

In [62]:
import yfinance as yf

eicher = yf.download(
    "EICHERMOT.NS",
    start="2020-08-20",
    end="2020-08-27",
    auto_adjust=False
)

print(eicher)

[*********************100%***********************]  1 of 1 completed

Price         Adj Close        Close         High          Low         Open  \
Ticker     EICHERMOT.NS EICHERMOT.NS EICHERMOT.NS EICHERMOT.NS EICHERMOT.NS
Date
2020-08-20  2016.431396  2137.135010  2153.000000  2090.000000  2120.000000
2020-08-21  2047.666992  2170.239990  2184.399902  2148.000000  2170.000000
2020-08-24  2053.525879  2176.449951  2387.250000  2151.699951  2199.449951
2020-08-25  2092.021729  2217.250000  2250.000000  2182.149902  2214.000000
2020-08-26  2121.837158  2248.850098  2288.000000  2235.000000  2280.050049

Price            Volume
Ticker     EICHERMOT.NS
Date
2020-08-20      2243200
2020-08-21      2613150
2020-08-24     11491305
2020-08-25      4757108
2020-08-26      2439339

In [63]:
eicher[('Adj Close', 'EICHERMOT.NS')].pct_change()

Date
2020-08-20         NaN
2020-08-21    0.015491
2020-08-24    0.002861
2020-08-25    0.018746
2020-08-26    0.014252
Name: (Adj Close, EICHERMOT.NS), dtype: float64

In [64]:
tickers = sorted(df['CanonicalSymbol'].unique())

print(len(tickers))
print(tickers)

50
['ADANIPORTS', 'ASIANPAINT', 'AXISBANK', 'BAJAJ-AUTO', 'BAJAJFINSV', 'BAJFINANCE', 'BHARTIARTL', 'BPCL', 'BRITANNIA', 'CIPLA', 'COALINDIA', 'DRREDDY', 'EICHERMOT', 'GAIL', 'GRASIM', 'HCLTECH', 'HDFC', 'HDFCBANK', 'HEROMOTOCO', 'HINDALCO', 'HINDUNILVR', 'ICICIBANK', 'INDUSINDBK', 'INFY', 'IOC', 'ITC', 'JSWSTEEL', 'KOTAKBANK', 'LT', 'M&M', 'MARUTI', 'NESTLEIND', 'NTPC', 'ONGC', 'POWERGRID', 'RELIANCE', 'SBIN', 'SHREECEM', 'SUNPHARMA', 'TATAMOTORS', 'TATASTEEL', 'TCS', 'TECHM', 'TITAN', 'ULTRACEMCO', 'UPL', 'UTIBANK', 'VEDL', 'WIPRO', 'ZEEL']

In [65]:
df['CanonicalSymbol'] = df['CanonicalSymbol'].replace({
    'UTIBANK': 'AXISBANK'
})

tickers = sorted(df['CanonicalSymbol'].unique())

print(len(tickers))

49

In [66]:
import yfinance as yf
import pandas as pd

adjusted_prices = {}

for ticker in tickers:
    try:
        data = yf.download(
            f"{ticker}.NS",
            start="2000-01-01",
            end="2021-05-01",
            auto_adjust=False,
            progress=False
        )

        if not data.empty:
            adjusted_prices[ticker] = data['Adj Close']
            print(f"{ticker}: {len(data)} rows")
        else:
            print(f"{ticker}: NO DATA")

    except Exception as e:
        print(f"{ticker}: ERROR - {e}")

ADANIPORTS: 3305 rows
ASIANPAINT: 4679 rows
AXISBANK: 5329 rows
BAJAJ-AUTO: 4682 rows
BAJAJFINSV: 4648 rows
BAJFINANCE: 4679 rows
BHARTIARTL: 4679 rows
BPCL: 5329 rows
BRITANNIA: 5332 rows
CIPLA: 5331 rows
COALINDIA: 2582 rows
DRREDDY: 5329 rows
EICHERMOT: 5329 rows
GAIL: 5329 rows
GRASIM: 4679 rows
HCLTECH: 4653 rows

$HDFC.NS: possibly delisted; no timezone found

1 Failed download:
['HDFC.NS']: possibly delisted; no timezone found

HDFC: NO DATA
HDFCBANK: 5332 rows
HEROMOTOCO: 4679 rows
HINDALCO: 5332 rows
HINDUNILVR: 5332 rows
ICICIBANK: 4679 rows
INDUSINDBK: 4680 rows
INFY: 5332 rows
IOC: 5329 rows
ITC: 5329 rows
JSWSTEEL: 4459 rows
KOTAKBANK: 4941 rows
LT: 4682 rows
M&M: 5330 rows
MARUTI: 4415 rows
NESTLEIND: 4652 rows
NTPC: 4068 rows
ONGC: 5329 rows
POWERGRID: 3341 rows
RELIANCE: 5329 rows
SBIN: 5330 rows
SHREECEM: 4939 rows
SUNPHARMA: 5332 rows

HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: TATAMOTORS.NS"}}}
$TATAMOTORS.NS: possibly delisted; no timezone found

1 Failed download:
['TATAMOTORS.NS']: possibly delisted; no timezone found

TATAMOTORS: NO DATA
TATASTEEL: 5332 rows
TCS: 4650 rows
TECHM: 3616 rows
TITAN: 5332 rows
ULTRACEMCO: 4649 rows
UPL: 4680 rows
VEDL: 5332 rows
WIPRO: 5332 rows
ZEEL: 4679 rows

In [67]:
print("Downloaded:", len(adjusted_prices))
print("Missing:", set(tickers) - set(adjusted_prices.keys()))

Downloaded: 47
Missing: {'HDFC', 'TATAMOTORS'}

In [68]:
id="q4w7zq"
print(adjusted_prices['EICHERMOT'].head())
print(adjusted_prices['EICHERMOT'].tail())

Ticker      EICHERMOT.NS
Date
2000-01-03      2.953003
2000-01-04      3.107150
2000-01-05      3.358020
2000-01-06      3.627024
2000-01-07      3.908119
Ticker      EICHERMOT.NS
Date
2021-04-26   2236.002930
2021-04-27   2264.544434
2021-04-28   2378.804932
2021-04-29   2323.797363
2021-04-30   2284.876953

In [69]:
adjusted_returns = {}

for ticker, series in adjusted_prices.items():
    adjusted_returns[ticker] = series.pct_change()

print(adjusted_returns['EICHERMOT'].loc['2020-08-20':'2020-08-26'])

Ticker      EICHERMOT.NS
Date
2020-08-20      0.005174
2020-08-21      0.015490
2020-08-24      0.002861
2020-08-25      0.018746
2020-08-26      0.014252

In [70]:
# Create a single DataFrame of adjusted returns
adj_returns_df = pd.concat(adjusted_returns, axis=1)

# Remove the Yahoo ticker level from columns
adj_returns_df.columns = adj_returns_df.columns.get_level_values(0)

# Convert Date into a column
adj_returns_df = adj_returns_df.reset_index()

print(adj_returns_df.head())
print(adj_returns_df.shape)

        Date  ADANIPORTS  ASIANPAINT  AXISBANK  BAJAJ-AUTO  BAJAJFINSV  \
0 2000-01-03         NaN         NaN       NaN         NaN         NaN
1 2000-01-04         NaN         NaN  0.038610         NaN         NaN
2 2000-01-05         NaN         NaN -0.026022         NaN         NaN
3 2000-01-06         NaN         NaN -0.024809         NaN         NaN
4 2000-01-07         NaN         NaN -0.048924         NaN         NaN

   BAJFINANCE  BHARTIARTL      BPCL  BRITANNIA  ...  SUNPHARMA  TATASTEEL  \
0         NaN         NaN       NaN        NaN  ...        NaN        NaN
1         NaN         NaN -0.072010  -0.003105  ...  -0.013406  -0.010824
2         NaN         NaN -0.028475  -0.025512  ...  -0.035102   0.038130
3         NaN         NaN  0.056536   0.068475  ...  -0.000973   0.074737
4         NaN         NaN -0.001183   0.079998  ...  -0.079991   0.021991

   TCS  TECHM     TITAN  ULTRACEMCO  UPL      VEDL     WIPRO  ZEEL
0  NaN    NaN       NaN         NaN  NaN       NaN       NaN   NaN
1  NaN    NaN -0.053308         NaN  NaN -0.014181  0.080005   NaN
2  NaN    NaN -0.061058         NaN  NaN -0.006103  0.016298   NaN
3  NaN    NaN  0.080202         NaN  NaN  0.046492 -0.019347   NaN
4  NaN    NaN -0.021070         NaN  NaN -0.023470 -0.079990   NaN

[5 rows x 48 columns]
(5333, 48)

C:\Users\Atharva\AppData\Local\Temp\ipykernel_21344\4060349245.py:2: Pandas4Warning: Sorting by default when concatenating all DatetimeIndex is deprecated.  In the future, pandas will respect the default of `sort=False`. Specify `sort=True` or `sort=False` to silence this message. If you see this warnings when not directly calling concat, report a bug to pandas.
  adj_returns_df = pd.concat(adjusted_returns, axis=1)

In [71]:
df = df.merge(
    adj_returns_df,
    on='Date',
    how='left',
    suffixes=('', '_Yahoo')
)

print(df.shape)

(235192, 69)

In [72]:
df['Adj_Return'] = df.apply(
    lambda row: (
        row['CanonicalSymbol']
        if False else None
    ),
    axis=1
)

In [73]:
df['Adj_Return'] = [
    row.get(row['CanonicalSymbol'])
    for _, row in df.iterrows()
]

In [74]:
print(df[['Date', 'CanonicalSymbol', 'Adj_Return']].head(20))

         Date CanonicalSymbol  Adj_Return
0  2007-11-27      ADANIPORTS         NaN
1  2007-11-28      ADANIPORTS   -0.077164
2  2007-11-29      ADANIPORTS    0.002260
3  2007-11-30      ADANIPORTS    0.047351
4  2007-12-03      ADANIPORTS    0.054898
5  2007-12-04      ADANIPORTS    0.070408
6  2007-12-05      ADANIPORTS    0.033365
7  2007-12-06      ADANIPORTS    0.005627
8  2007-12-07      ADANIPORTS    0.009082
9  2007-12-10      ADANIPORTS   -0.024045
10 2007-12-11      ADANIPORTS   -0.025662
11 2007-12-12      ADANIPORTS   -0.008700
12 2007-12-13      ADANIPORTS    0.090896
13 2007-12-14      ADANIPORTS   -0.021350
14 2007-12-17      ADANIPORTS   -0.056685
15 2007-12-18      ADANIPORTS    0.000000
16 2007-12-19      ADANIPORTS    0.021690
17 2007-12-20      ADANIPORTS   -0.006280
18 2007-12-24      ADANIPORTS    0.091115
19 2007-12-26      ADANIPORTS    0.037258

In [75]:
# Replace raw return with corporate-action-adjusted return
df['Return'] = df['Adj_Return']

# Recalculate 20-day volatility using adjusted returns
df = df.sort_values(['CanonicalSymbol', 'Date'])

df['Volatility_20'] = (
    df.groupby('CanonicalSymbol')['Return']
      .transform(lambda x: x.rolling(20).std())
)

print(df[['Date', 'CanonicalSymbol', 'Return', 'Volatility_20']].head(25))

         Date CanonicalSymbol    Return  Volatility_20
0  2007-11-27      ADANIPORTS       NaN            NaN
1  2007-11-28      ADANIPORTS -0.077164            NaN
2  2007-11-29      ADANIPORTS  0.002260            NaN
3  2007-11-30      ADANIPORTS  0.047351            NaN
4  2007-12-03      ADANIPORTS  0.054898            NaN
5  2007-12-04      ADANIPORTS  0.070408            NaN
6  2007-12-05      ADANIPORTS  0.033365            NaN
7  2007-12-06      ADANIPORTS  0.005627            NaN
8  2007-12-07      ADANIPORTS  0.009082            NaN
9  2007-12-10      ADANIPORTS -0.024045            NaN
10 2007-12-11      ADANIPORTS -0.025662            NaN
11 2007-12-12      ADANIPORTS -0.008700            NaN
12 2007-12-13      ADANIPORTS  0.090896            NaN
13 2007-12-14      ADANIPORTS -0.021350            NaN
14 2007-12-17      ADANIPORTS -0.056685            NaN
15 2007-12-18      ADANIPORTS  0.000000            NaN
16 2007-12-19      ADANIPORTS  0.021690            NaN
17 2007-12-20      ADANIPORTS -0.006280            NaN
18 2007-12-24      ADANIPORTS  0.091115            NaN
19 2007-12-26      ADANIPORTS  0.037258            NaN
20 2007-12-27      ADANIPORTS  0.009793       0.044555
21 2007-12-28      ADANIPORTS  0.030908       0.039330
22 2007-12-31      ADANIPORTS  0.015771       0.039160
23 2008-01-01      ADANIPORTS  0.022107       0.038593
24 2008-01-02      ADANIPORTS  0.008174       0.037612

In [76]:
print(
    df[
        (df['CanonicalSymbol'] == 'EICHERMOT') &
        (df['Date'].between('2020-08-20', '2020-08-26'))
    ][['Date', 'Return', 'Volatility_20', 'Volume_Ratio']]
)

            Date    Return  Volatility_20  Volume_Ratio
57383 2020-08-20  0.005174       0.026829      0.818705
57384 2020-08-21  0.015490       0.026973      0.977547
57385 2020-08-24  0.002861       0.026738     13.807329
57386 2020-08-25  0.018746       0.026502      4.500438
57387 2020-08-26  0.014252       0.026445      2.089139

In [77]:
print(
    df[
        (df['CanonicalSymbol'] == 'EICHERMOT') &
        (df['Date'].between('2020-08-20', '2020-08-26'))
    ][['Date', 'Volume', 'Volume_Ratio']]
)

            Date    Volume  Volume_Ratio
57383 2020-08-20    224320      0.818705
57384 2020-08-21    261318      0.977547
57385 2020-08-24  11491732     13.807329
57386 2020-08-25   4757114      4.500438
57387 2020-08-26   2439450      2.089139

In [78]:
eicher_actions = yf.Ticker("EICHERMOT.NS").actions

print(
    eicher_actions[
        (eicher_actions.index >= '2020-08-20') &
        (eicher_actions.index <= '2020-08-26')
    ]
)

                           Dividends  Stock Splits
Date
2020-08-24 00:00:00+05:30        0.0          10.0

In [79]:
df.loc[
    (df['CanonicalSymbol'] == 'EICHERMOT') &
    (df['Date'].between('2020-08-20', '2020-08-26')),
    ['Date', 'Volume']
]

            Date    Volume
57383 2020-08-20    224320
57384 2020-08-21    261318
57385 2020-08-24  11491732
57386 2020-08-25   4757114
57387 2020-08-26   2439450

In [80]:
print("Split factor:", 10)

print("Pre-split volume:", 261318)
print("Expected comparable volume:", 261318 * 10)
print("Split-day volume:", 11491732)

Split factor: 10
Pre-split volume: 261318
Expected comparable volume: 2613180
Split-day volume: 11491732

In [81]:
split_data = {}

for ticker in tickers:
    try:
        actions = yf.Ticker(f"{ticker}.NS").actions
        splits = actions[actions['Stock Splits'] != 0]['Stock Splits']

        split_data[ticker] = splits

        if len(splits) > 0:
            print(f"{ticker}:")
            print(splits)
    except Exception as e:
        print(f"{ticker}: ERROR - {e}")

ADANIPORTS:
Date
2010-09-23 00:00:00+05:30    5.0
Name: Stock Splits, dtype: float64
ASIANPAINT:
Date
2003-08-22 00:00:00+05:30     1.5
2013-07-30 00:00:00+05:30    10.0
Name: Stock Splits, dtype: float64
AXISBANK:
Date
2014-07-28 00:00:00+05:30    5.0
Name: Stock Splits, dtype: float64
BAJAJ-AUTO:
Date
2010-09-08 00:00:00+05:30    2.0
Name: Stock Splits, dtype: float64
BAJAJFINSV:
Date
2022-09-13 00:00:00+05:30    5.0
Name: Stock Splits, dtype: float64
BAJFINANCE:
Date
2016-09-08 00:00:00+05:30    5.0
2025-06-16 00:00:00+05:30    2.0
Name: Stock Splits, dtype: float64
BHARTIARTL:
Date
2009-07-24 00:00:00+05:30    2.0
Name: Stock Splits, dtype: float64
BPCL:
Date
2000-12-20 00:00:00+05:30    2.0
2012-07-13 00:00:00+05:30    2.0
2016-07-13 00:00:00+05:30    2.0
2017-07-13 00:00:00+05:30    1.5
2024-06-21 00:00:00+05:30    2.0
Name: Stock Splits, dtype: float64
BRITANNIA:
Date
1999-09-24 00:00:00+05:30    1.5
2010-09-08 00:00:00+05:30    5.0
2018-11-29 00:00:00+05:30    2.0
Name: Stock Splits, dtype: float64
CIPLA:
Date
1999-10-18 00:00:00+05:30    3.0
2004-05-11 00:00:00+05:30    5.0
2006-04-24 00:00:00+05:30    2.5
Name: Stock Splits, dtype: float64
COALINDIA: ERROR - 'Stock Splits'
DRREDDY:
Date
2001-10-10 00:00:00+05:30    2.0
2006-08-28 00:00:00+05:30    2.0
2024-10-28 00:00:00+05:30    5.0
Name: Stock Splits, dtype: float64
EICHERMOT:
Date
2020-08-24 00:00:00+05:30    10.0
Name: Stock Splits, dtype: float64
GAIL:
Date
2008-10-06 00:00:00+05:30    1.500000
2017-03-09 00:00:00+05:30    1.333333
2018-03-27 00:00:00+05:30    1.333333
2019-07-09 00:00:00+05:30    2.000000
2022-09-06 00:00:00+05:30    1.500000
Name: Stock Splits, dtype: float64
GRASIM:
Date
2016-10-06 00:00:00+05:30    5.0
Name: Stock Splits, dtype: float64
HCLTECH:
Date
2007-03-15 00:00:00+05:30    2.0
2015-03-19 00:00:00+05:30    2.0
2019-12-05 00:00:00+05:30    2.0
Name: Stock Splits, dtype: float64

$HDFC.NS: possibly delisted; no timezone found

HDFC: ERROR - 'Stock Splits'
HDFCBANK:
Date
2011-07-14 00:00:00+05:30    5.0
2019-09-19 00:00:00+05:30    2.0
2025-08-26 00:00:00+05:30    2.0
Name: Stock Splits, dtype: float64
HEROMOTOCO: ERROR - 'Stock Splits'
HINDALCO:
Date
2005-08-30 00:00:00+05:30    10.0
Name: Stock Splits, dtype: float64
HINDUNILVR:
Date
2000-07-10 00:00:00+05:30    10.0
Name: Stock Splits, dtype: float64
ICICIBANK:
Date
2014-12-04 00:00:00+05:30    5.0
2017-06-20 00:00:00+05:30    1.1
Name: Stock Splits, dtype: float64
INDUSINDBK: ERROR - 'Stock Splits'
INFY:
Date
1997-08-19 00:00:00+05:30    2.0
1999-02-10 00:00:00+05:30    2.0
2000-01-27 00:00:00+05:30    2.0
2004-07-01 00:00:00+05:30    4.0
2006-07-13 00:00:00+05:30    2.0
2014-12-02 00:00:00+05:30    2.0
2015-06-15 00:00:00+05:30    2.0
2018-09-04 00:00:00+05:30    2.0
Name: Stock Splits, dtype: float64
IOC:
Date
1999-09-27 00:00:00+05:30    2.0
2003-08-14 00:00:00+05:30    1.5
2009-10-29 00:00:00+05:30    2.0
2016-10-18 00:00:00+05:30    2.0
2018-03-15 00:00:00+05:30    2.0
2022-06-30 00:00:00+05:30    1.5
Name: Stock Splits, dtype: float64
ITC:
Date
2005-09-21 00:00:00+05:30    10.0
2010-08-03 00:00:00+05:30     2.0
2016-07-01 00:00:00+05:30     1.5
Name: Stock Splits, dtype: float64
JSWSTEEL:
Date
2005-02-21 00:00:00+05:30     0.04375
2017-01-04 00:00:00+05:30    10.00000
Name: Stock Splits, dtype: float64
KOTAKBANK:
Date
2004-08-25 00:00:00+05:30    2.0
2005-08-25 00:00:00+05:30    2.5
2010-09-13 00:00:00+05:30    2.0
2015-07-08 00:00:00+05:30    2.0
2026-01-14 00:00:00+05:30    5.0
Name: Stock Splits, dtype: float64
LT:
Date
2004-05-19 00:00:00+05:30    0.5
2006-09-28 00:00:00+05:30    2.0
2008-10-01 00:00:00+05:30    2.0
2013-07-11 00:00:00+05:30    1.5
2017-07-13 00:00:00+05:30    1.5
Name: Stock Splits, dtype: float64
M&M:
Date
2005-09-01 00:00:00+05:30    2.0
2010-03-29 00:00:00+05:30    2.0
2017-12-21 00:00:00+05:30    2.0
Name: Stock Splits, dtype: float64
MARUTI: ERROR - 'Stock Splits'
NESTLEIND:
Date
2024-01-05 00:00:00+05:30    10.0
2025-08-08 00:00:00+05:30     2.0
Name: Stock Splits, dtype: float64
NTPC:
Date
2019-03-19 00:00:00+05:30    1.2
Name: Stock Splits, dtype: float64
ONGC:
Date
2006-10-27 00:00:00+05:30    1.5
2011-02-08 00:00:00+05:30    2.0
2016-12-15 00:00:00+05:30    1.5
Name: Stock Splits, dtype: float64
POWERGRID:
Date
2021-07-29 00:00:00+05:30    1.333333
2023-09-12 00:00:00+05:30    1.333333
Name: Stock Splits, dtype: float64
RELIANCE:
Date
1997-10-27 00:00:00+05:30    2.0
2009-11-26 00:00:00+05:30    2.0
2017-09-07 00:00:00+05:30    2.0
2024-10-28 00:00:00+05:30    2.0
Name: Stock Splits, dtype: float64
SBIN:
Date
2014-11-20 00:00:00+05:30    10.0
Name: Stock Splits, dtype: float64
SHREECEM: ERROR - 'Stock Splits'

$TATAMOTORS.NS: possibly delisted; no timezone found

SUNPHARMA:
Date
2000-03-08 00:00:00+05:30    3.0
2003-01-13 00:00:00+05:30    2.0
2004-05-27 00:00:00+05:30    2.0
2010-11-25 00:00:00+05:30    5.0
2013-07-29 00:00:00+05:30    2.0
Name: Stock Splits, dtype: float64
TATAMOTORS: ERROR - 'Stock Splits'
TATASTEEL:
Date
2004-08-11 00:00:00+05:30     1.5
2022-07-28 00:00:00+05:30    10.0
Name: Stock Splits, dtype: float64
TCS:
Date
2006-07-28 00:00:00+05:30    2.0
2009-06-16 00:00:00+05:30    2.0
2018-05-31 00:00:00+05:30    2.0
Name: Stock Splits, dtype: float64
TECHM:
Date
2015-03-19 00:00:00+05:30    2.0
Name: Stock Splits, dtype: float64
TITAN:
Date
2011-06-23 00:00:00+05:30    10.0
Name: Stock Splits, dtype: float64
ULTRACEMCO: ERROR - 'Stock Splits'
UPL:
Date
2005-09-27 00:00:00+05:30    5.0
2008-10-29 00:00:00+05:30    2.0
2019-07-02 00:00:00+05:30    1.5
Name: Stock Splits, dtype: float64
VEDL:
Date
2005-02-16 00:00:00+05:30     2.0
2008-08-08 00:00:00+05:30    10.0
Name: Stock Splits, dtype: float64
WIPRO:
Date
1997-10-20 00:00:00+05:30    3.000000
1999-09-27 00:00:00+05:30    5.000000
2004-06-25 00:00:00+05:30    3.000000
2005-08-22 00:00:00+05:30    2.000000
2010-06-15 00:00:00+05:30    1.666667
2017-06-13 00:00:00+05:30    2.000000
2019-03-06 00:00:00+05:30    1.333333
2024-12-03 00:00:00+05:30    2.000000
Name: Stock Splits, dtype: float64
ZEEL:
Date
2010-11-11 00:00:00+05:30    2.0
Name: Stock Splits, dtype: float64

In [82]:
def get_split_factor(ticker, date):
    splits = split_data.get(ticker)

    if splits is None or len(splits) == 0:
        return 1.0

    factor = 1.0

    for split_date, split_ratio in splits.items():
        split_date = split_date.tz_localize(None)

        if date < split_date:
            factor *= split_ratio

    return factor


# Test EICHERMOT
for date in pd.to_datetime([
    '2020-08-20',
    '2020-08-21',
    '2020-08-24',
    '2020-08-25'
]):
    print(date.date(), get_split_factor('EICHERMOT', date))

2020-08-20 10.0
2020-08-21 10.0
2020-08-24 1.0
2020-08-25 1.0

In [83]:
eicher_test = df[df['CanonicalSymbol'] == 'EICHERMOT'].copy()

eicher_test['Split_Factor'] = eicher_test['Date'].apply(
    lambda x: get_split_factor('EICHERMOT', x)
)

eicher_test['Adjusted_Volume'] = (
    eicher_test['Volume'] * eicher_test['Split_Factor']
)

print(
    eicher_test[
        eicher_test['Date'].between('2020-08-20', '2020-08-26')
    ][['Date', 'Volume', 'Split_Factor', 'Adjusted_Volume']]
)

            Date    Volume  Split_Factor  Adjusted_Volume
57383 2020-08-20    224320          10.0        2243200.0
57384 2020-08-21    261318          10.0        2613180.0
57385 2020-08-24  11491732           1.0       11491732.0
57386 2020-08-25   4757114           1.0        4757114.0
57387 2020-08-26   2439450           1.0        2439450.0

In [84]:
eicher_test['Volume_MA_20_Adjusted'] = (
    eicher_test['Adjusted_Volume']
    .rolling(20)
    .mean()
)

eicher_test['Volume_Ratio_Adjusted'] = (
    eicher_test['Adjusted_Volume']
    / eicher_test['Volume_MA_20_Adjusted']
)

print(
    eicher_test[
        eicher_test['Date'].between('2020-08-20', '2020-08-26')
    ][['Date', 'Adjusted_Volume', 'Volume_Ratio_Adjusted']]
)

            Date  Adjusted_Volume  Volume_Ratio_Adjusted
57383 2020-08-20        2243200.0               0.818705
57384 2020-08-21        2613180.0               0.977547
57385 2020-08-24       11491732.0               3.646268
57386 2020-08-25        4757114.0               1.459975
57387 2020-08-26        2439450.0               0.746675

In [85]:
df['Split_Factor'] = [
    get_split_factor(ticker, date)
    for ticker, date in zip(df['CanonicalSymbol'], df['Date'])
]

df['Adjusted_Volume'] = (
    df['Volume'] * df['Split_Factor']
)

df = df.sort_values(['CanonicalSymbol', 'Date'])

df['Volume_MA_20'] = (
    df.groupby('CanonicalSymbol')['Adjusted_Volume']
      .transform(lambda x: x.rolling(20).mean())
)

df['Volume_Ratio'] = (
    df['Adjusted_Volume'] / df['Volume_MA_20']
)

In [86]:
print(
    df[
        (df['CanonicalSymbol'] == 'EICHERMOT') &
        (df['Date'].between('2020-08-20', '2020-08-26'))
    ][['Date', 'Return', 'Volatility_20', 'Volume_Ratio']]
)

            Date    Return  Volatility_20  Volume_Ratio
57383 2020-08-20  0.005174       0.026829      0.818705
57384 2020-08-21  0.015490       0.026973      0.977547
57385 2020-08-24  0.002861       0.026738      3.646268
57386 2020-08-25  0.018746       0.026502      1.459975
57387 2020-08-26  0.014252       0.026445      0.746675

In [87]:
features = ['Return', 'Volatility_20', 'Volume_Ratio']

model_df = df.dropna(subset=features).copy()

train_df = model_df[model_df['Date'] < '2016-01-01']
test_df = model_df[model_df['Date'] >= '2016-01-01']

X_train = train_df[features]
X_test = test_df[features]

print("Train:", X_train.shape)
print("Test:", X_test.shape)

Train: (131667, 3)
Test: (58186, 3)

In [88]:
from sklearn.ensemble import IsolationForest

model = IsolationForest(
    n_estimators=200,
    contamination=0.01,
    random_state=42,
    n_jobs=-1
)

model.fit(X_train)

test_df['Anomaly'] = model.predict(X_test)
test_df['Anomaly_Score'] = model.decision_function(X_test)

print(test_df['Anomaly'].value_counts())

Anomaly
 1    57933
-1      253
Name: count, dtype: int64

In [89]:
print(
    test_df[test_df['Anomaly'] == -1]
    .sort_values('Anomaly_Score')
    [['Date', 'CanonicalSymbol', 'Return',
      'Volatility_20', 'Volume_Ratio', 'Anomaly_Score']]
    .head(20)
)

             Date CanonicalSymbol    Return  Volatility_20  Volume_Ratio  \
174083 2017-10-25            SBIN  0.276872       0.063890     10.375999
234634 2019-01-28            ZEEL  0.172425       0.073455      8.131119
207969 2017-06-05           TITAN  0.169793       0.042725      9.702866
208074 2017-11-06           TITAN  0.187874       0.044669      9.411944
234633 2019-01-25            ZEEL -0.266106       0.059943      8.263567
229687 2020-07-15           WIPRO  0.167778       0.039984      9.170861
33105  2018-10-05            BPCL -0.198852       0.057352      7.005675
109690 2020-03-18      INDUSINDBK -0.237276       0.068229      5.092818
216679 2018-07-23             UPL  0.150109       0.040689      6.758627
119945 2018-10-05             IOC -0.158589       0.046280      6.827230
224026 2019-02-01            VEDL -0.178363       0.042486      7.311273
109696 2020-03-26      INDUSINDBK  0.446731       0.136945      2.014109
52103  2020-09-18         DRREDDY  0.104842       0.029853      8.592714
33543  2020-07-17            BPCL  0.126682       0.038461      6.406898
234832 2019-11-21            ZEEL  0.124267       0.061792      4.418647
109699 2020-03-31      INDUSINDBK -0.150218       0.139246      1.529716
124949 2017-07-18             ITC -0.124865       0.035447      7.667055
160704 2020-03-18            ONGC  0.135834       0.062971      4.055650
234914 2020-03-18            ZEEL  0.232908       0.087698      2.708816
137828 2016-05-26              LT  0.141336       0.035582      6.294456

        Anomaly_Score
174083      -0.128674
234634      -0.122758
207969      -0.113438
208074      -0.111588
234633      -0.105260
229687      -0.103995
33105       -0.096405
109690      -0.091039
216679      -0.088462
119945      -0.087817
224026      -0.087162
109696      -0.085572
52103       -0.081108
33543       -0.080887
234832      -0.080785
109699      -0.079448
124949      -0.078802
160704      -0.077242
234914      -0.077027
137828      -0.076839

In [90]:
print(
    test_df[test_df['Anomaly'] == -1]['Return']
    .abs()
    .describe()
)

count    253.000000
mean       0.102010
std        0.055901
min        0.000113
25%        0.073949
50%        0.095513
75%        0.127725
max        0.446731
Name: Return, dtype: float64

In [91]:
print(
    "Abs return > 50%:",
    (test_df.loc[test_df['Anomaly'] == -1, 'Return'].abs() > 0.50).sum()
)

Abs return > 50%: 0

In [92]:
covid_anomalies = test_df[
    (test_df['Date'] >= '2020-02-01') &
    (test_df['Date'] <= '2020-04-30') &
    (test_df['Anomaly'] == -1)
].sort_values('Anomaly_Score')

print(
    covid_anomalies[
        ['Date', 'CanonicalSymbol', 'Return',
         'Volatility_20', 'Volume_Ratio', 'Anomaly_Score']
    ].to_string(index=False)
)

print("\nTotal COVID-period anomalies:", len(covid_anomalies))

      Date CanonicalSymbol    Return  Volatility_20  Volume_Ratio  Anomaly_Score
2020-03-18      INDUSINDBK -0.237276       0.068229      5.092818      -0.091039
2020-03-26      INDUSINDBK  0.446731       0.136945      2.014109      -0.085572
2020-03-31      INDUSINDBK -0.150218       0.139246      1.529716      -0.079448
2020-03-18            ONGC  0.135834       0.062971      4.055650      -0.077242
2020-03-18            ZEEL  0.232908       0.087698      2.708816      -0.077027
2020-04-28      INDUSINDBK  0.148871       0.131468      1.847057      -0.074426
2020-04-07      INDUSINDBK  0.225575       0.151329      1.541645      -0.074032
2020-03-20            ONGC  0.185094       0.080060      2.541691      -0.070531
2020-04-22            ZEEL  0.174855       0.071618      3.122666      -0.069951
2020-04-21      INDUSINDBK -0.122290       0.140841      0.915037      -0.068319
2020-04-09          MARUTI  0.133788       0.079687      2.179076      -0.053528
2020-03-19            ZEEL -0.139549       0.091335      1.263901      -0.053508
2020-04-07        HINDALCO  0.170608       0.077156      1.828055      -0.052941
2020-03-23            ZEEL -0.158040       0.095496      0.616049      -0.051301
2020-03-17            ZEEL -0.199880       0.065801      2.757764      -0.051292
2020-04-07            ZEEL  0.133092       0.102047      0.736572      -0.051170
2020-04-03      INDUSINDBK -0.084879       0.138496      0.830693      -0.050879
2020-04-07        AXISBANK  0.194807       0.095534      1.329305      -0.050687
2020-04-15             UPL  0.078781       0.070890      3.767601      -0.050653
2020-04-17      INDUSINDBK  0.089688       0.149403      0.754953      -0.049225
2020-04-30             UPL  0.164864       0.053319      3.015800      -0.048380
2020-04-09           CIPLA  0.130375       0.055195      3.077499      -0.046925
2020-04-17        AXISBANK  0.133120       0.095955      1.075235      -0.046109
2020-03-23        AXISBANK -0.279108       0.069993      2.043942      -0.045381
2020-04-13            ZEEL -0.085085       0.098763      1.819768      -0.043897
2020-04-22        RELIANCE  0.102032       0.066616      2.927120      -0.043360
2020-03-30      BAJFINANCE -0.118082       0.081504      1.687991      -0.041450
2020-04-15      HINDUNILVR  0.060133       0.058987      5.294906      -0.040913
2020-04-30        HINDALCO  0.119518       0.064838      2.237109      -0.038671
2020-03-23      INDUSINDBK -0.235949       0.077580      0.595530      -0.036886
2020-04-07          MARUTI  0.135149       0.072471      1.769157      -0.036446
2020-04-09             M&M  0.168505       0.073964      1.452136      -0.034446
2020-03-23      BAJAJFINSV -0.258621       0.068686      1.504529      -0.034349
2020-04-13      BAJFINANCE -0.103670       0.088598      1.237375      -0.033957
2020-04-07          GRASIM  0.140422       0.078862      0.800033      -0.031110
2020-04-07      HINDUNILVR  0.134999       0.059017      2.252617      -0.029936
2020-04-07       ICICIBANK  0.137624       0.074034      1.064689      -0.029245
2020-03-23            VEDL -0.169649       0.071885      0.736092      -0.029121
2020-03-27      BAJFINANCE -0.089988       0.079257      1.621299      -0.028588
2020-03-25        RELIANCE  0.147180       0.069598      1.577770      -0.028244
2020-03-23            ONGC -0.103192       0.082239      0.706306      -0.027352
2020-03-27      INDUSINDBK -0.056894       0.136906      1.919356      -0.026547
2020-04-07        RELIANCE  0.119402       0.077612      1.063035      -0.026068
2020-03-23      BAJFINANCE -0.232308       0.066947      1.425758      -0.025799
2020-04-07       SUNPHARMA  0.110121       0.054931      2.453703      -0.025698
2020-03-09            ONGC -0.157627       0.039753      3.210769      -0.024989
2020-04-21      BAJFINANCE -0.090328       0.085290      0.980867      -0.024823
2020-03-31            BPCL  0.153412       0.070322      1.336749      -0.024417
2020-04-03        AXISBANK -0.092569       0.080890      1.204582      -0.024300
2020-04-21        AXISBANK -0.077421       0.097530      0.739010      -0.023872
2020-03-18       POWERGRID -0.110185       0.037261      3.567002      -0.023748
2020-03-25        AXISBANK  0.078014       0.074348      2.266492      -0.023468
2020-04-24      INDUSINDBK -0.065984       0.130229      0.608061      -0.022889
2020-04-23            ZEEL  0.037537       0.071830      3.825883      -0.022313
2020-04-07        JSWSTEEL  0.123668       0.069703      1.527440      -0.021635
2020-04-27      INDUSINDBK  0.063985       0.129092      0.843420      -0.021565
2020-03-24      INDUSINDBK -0.071630       0.076812      2.132048      -0.021026
2020-04-09      BAJFINANCE  0.093853       0.086713      1.133965      -0.019502
2020-04-17       EICHERMOT  0.104627       0.050535      2.718884      -0.019396
2020-04-07            BPCL  0.107047       0.075907      0.796734      -0.019058
2020-03-13            SBIN  0.138288       0.052245      2.214122      -0.018312
2020-03-25      ADANIPORTS  0.102913       0.065978      1.772284      -0.017886
2020-04-09           TITAN  0.109913       0.060944      2.011583      -0.017793
2020-03-25          GRASIM  0.128093       0.068528      1.182363      -0.016850
2020-04-07           CIPLA  0.095837       0.048535      3.063987      -0.015017
2020-03-20            GAIL  0.164265       0.061375      1.608884      -0.014518
2020-04-21        HINDALCO -0.080292       0.074339      1.371475      -0.014296
2020-03-09        RELIANCE -0.123407       0.031333      3.478848      -0.013837
2020-04-09        AXISBANK  0.073591       0.097695      1.095002      -0.013218
2020-03-12            ONGC -0.128312       0.046381      2.430294      -0.013074
2020-03-24      BAJFINANCE  0.091808       0.072665      1.715511      -0.012395
2020-03-31            ONGC  0.078137       0.086343      0.828374      -0.010730
2020-03-19            ONGC -0.104182       0.065834      1.351746      -0.010596
2020-04-07         DRREDDY  0.138681       0.047318      2.251595      -0.010061
2020-04-21       ICICIBANK -0.081511       0.074203      0.867180      -0.010002
2020-04-17       ICICIBANK  0.098099       0.074503      1.191425      -0.009809
2020-03-19      BAJFINANCE -0.102977       0.044377      2.783908      -0.008786
2020-04-07             UPL  0.085709       0.073408      0.700261      -0.007047
2020-04-08      INDUSINDBK  0.039859       0.152320      1.774350      -0.006307
2020-04-07             M&M  0.143570       0.060830      1.526459      -0.005730
2020-03-09            VEDL -0.145430       0.049371      1.949870      -0.005135
2020-04-24      BAJFINANCE -0.090313       0.065242      1.328551      -0.004797
2020-03-26      BAJFINANCE  0.080484       0.077945      1.236014      -0.004511
2020-04-07       TATASTEEL  0.088473       0.068494      0.862809      -0.003750
2020-04-28      BAJFINANCE  0.090042       0.064717      1.688831      -0.003085
2020-03-25              LT  0.081720       0.052491      2.601818      -0.003059
2020-03-27        AXISBANK  0.053749       0.078094      2.463278      -0.002410
2020-04-01       KOTAKBANK -0.088268       0.063732      1.522822      -0.002186
2020-03-13       TATASTEEL  0.136545       0.051548      1.873649      -0.001719
2020-03-12            VEDL -0.132065       0.055237      1.722809      -0.001359
2020-04-09      HEROMOTOCO  0.092910       0.063608      1.703010      -0.001268
2020-04-09            VEDL  0.092461       0.070252      1.258802      -0.001176
2020-04-03       SUNPHARMA  0.094310       0.048796      2.571185      -0.000898
2020-03-25          MARUTI  0.115793       0.062251      1.306257      -0.000586
2020-03-31        RELIANCE  0.080839       0.072373      0.917341      -0.000017

Total COVID-period anomalies: 95